server {
    listen 80;
    server_name www.test.com test.com;
    access_log /var/log/nginx/test.access.log;
    error_log /var/log/nginx/test.error.log warn;

    include /etc/nginx/snippets/cloudflare-realip.conf;
    include /etc/nginx/snippets/security-headers.conf;

    charset utf-8;
    client_max_body_size 20M;

    location / {
        proxy_pass http://172.29.112.80:18080;

	    proxy_set_header Host $host;

        # 【核心修正】直接使用 realip 模块解析好的 $remote_addr
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header CF-Connecting-IP $remote_addr;

        # 伪 IPv4 依然使用原始 Header（如果 CF 开启了 Pseudo-IPv4，这里能拿到；没开启就是空）
        proxy_set_header Cf-Pseudo-IPv4 $http_cf_pseudo_ipv4;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}